const DEFAULT_QUIZ_DATA = [
    {
        id: "pension-1",
        title: "国民年金法 資格喪失の時期 (法9条) 強制被保険者",
        columns: ["項目", "当日喪失", "翌日喪失"],
        questions: [
            { id: "q-1", text: "イ）死亡したとき", answer: "翌日喪失" },
            { id: "q-2", text: "ニ）厚生年金保険法に基づく老齢給付等を受けることができる者その他この法律の適用を除外すべき特別の理由がある者として厚生労働省令で定める者となったとき（第2号被保険者又は第3号被保険者に該当するときを除く）", answer: "当日喪失" },
            { id: "q-3", text: "ハ）60歳に達したとき（第2号被保険者に該当するときを除く）", answer: "当日喪失" }
        ]
    },
    {
        id: "survivor-rank-1",
        title: "【特訓】遺族の順位判定（スリム版）",
        isMultiSelect: true,
        columns: [
            "順位", "【生計維持】", "【生計同一】", "配偶者", "子", "父母", "孫", "祖父母", "兄弟姉妹", "3親等以内", "対象なし"
        ],
        questions: [
            { id: "q-surv-1", text: "第1順位", answer: ["配偶者", "子", "【生計維持】"] },
            { id: "q-surv-2", text: "第2順位", answer: ["父母", "【生計維持】"] },
            { id: "q-surv-3", text: "第3順位", answer: ["孫", "【生計維持】"] },
            { id: "q-surv-4", text: "第4順位", answer: ["祖父母", "【生計維持】"] },
            { id: "q-surv-5", text: "第5順位", answer: ["対象なし"] },
            { id: "q-surv-6", text: "第6順位", answer: ["対象なし"] }
        ]
    },
    {
        id: "clause-sample-1",
        title: "雇用保険法 第1条（目的）",
        type: "clause",
        text: "雇用保険は、労働者が[[失業]]した場合及び労働者について[[雇用の継続]]が困難となる事由が生じた場合に必要な給付を行うほか、労働者が自ら職業に関する[[教育訓練]]を受けた場合並びに労働者が[[子を養育]]するための休業及び[[所定労働時間]]を短縮することによる就業をした場合に必要な給付を行うことにより、労働者の[[生活及び雇用]]の安定を図るとともに、[[求職活動]]を容易にする等その就職を促進し、あわせて、労働者の[[職業の安定]]に資するため、[[失業の予防]]、雇用状態の是正及び[[雇用機会の増大]]、労働者の[[能力の開発]]及び向上その他労働者の[[福祉の増進]]を図ることを目的とする。",
        dummies: ["老齢基礎年金", "厚生労働大臣", "60日以内"],
        questions: []
    }
];

// Spaced Repetition System (SRS) intervals in days
// Level 0: New, Level 1: 1 day, Level 2: 2 days, Level 3: 4 days, etc.
const SRS_INTERVALS = [0, 1, 2, 4, 7, 14, 30, 60, 120, 120, 120];


class QuizApp {
    constructor(initialData = {}) {
        this.quizData = initialData.quizData || JSON.parse(JSON.stringify(DEFAULT_QUIZ_DATA));
        this.history = initialData.history || [];
        this.questionStats = initialData.questionStats || {};
        this.currentSetId = this.quizData[0].id;
        this.isAutoGenerated = false;

        this.userAnswers = {};
        this.isChecked = false;
        this.isEditMode = false;
        this.selectedKeyword = null; // Track clicked keyword for "Click-to-Fill" fallback

        this.sortColumnIndex = -1;
        this.sortDirection = 1;

        this.stagnantSortKey = 'stagnantScore'; // Default sorting
        this.stagnantSortOrder = -1; // -1 for desc, 1 for asc

        // --- REFINED DATA RECOVERY ---
        const repairKey = 'sharoDataRepair_20260421v4_distributed';
        if (!localStorage.getItem(repairKey)) {
            console.log("Starting refined data recovery with distribution...");
            const now = new Date();
            const tomorrow = new Date(now);
            tomorrow.setDate(tomorrow.getDate() + 1);
            tomorrow.setHours(0, 0, 0, 0);

            let spreadCounter = 0;
            Object.values(this.questionStats).forEach(stat => {
                if (stat.nextReview && stat.history && stat.history.length > 0) {
                    const last = stat.history[stat.history.length - 1];
                    if (last.date) {
                        const lastDate = new Date(last.date);
                        const days = SRS_INTERVALS[stat.srsLevel || 0] || 0;
                        const originalNext = new Date(lastDate);
                        originalNext.setDate(originalNext.getDate() + days);
                        originalNext.setHours(0, 0, 0, 0);
                        
                        if (originalNext < tomorrow) {
                            // If it's overdue, spread it gently over the next 14 days
                            const offset = (spreadCounter % 14) + 1; // 1 to 14 days from now
                            const distributedNext = new Date(now);
                            distributedNext.setDate(distributedNext.getDate() + offset);
                            distributedNext.setHours(0, 0, 0, 0);
                            stat.nextReview = distributedNext.toISOString();
                            spreadCounter++;
                        } else {
                            // Keep the future date if it was originally in the future
                            stat.nextReview = originalNext.toISOString();
                        }
                    }
                }
            });
            localStorage.setItem(repairKey, 'done');
            setTimeout(() => { this.saveQuestionStats(); this.updateDashboard(); }, 1200);
        }
        // -----------------------------

        this.chartMode = 'accuracy';
        this.statsChart = null;
        this.srsProjectionChart = null;
        this.masteryHistogramChart = null;
        this.questionObserver = null;
        this.isBankMinimized = false; // Persistent state for the session
        this.dailyGoal = 50;
        this.ctxItemId = null; // Currently targeted item for context menu

        // Auto-fill settings
        const storedEnabled = localStorage.getItem('sharoAutoFillEnabled');
        this.autoFillEnabled = storedEnabled !== null ? JSON.parse(storedEnabled) : false;

        const storedThreshold = localStorage.getItem('sharoAutoFillThreshold');
        this.autoFillThreshold = storedThreshold !== null ? parseInt(storedThreshold) : 5;
        this.flashInterval = parseInt(localStorage.getItem('sharoFlashInterval') || '5', 10);
        this.flashTimer = null;

        const storedIgnore = localStorage.getItem('sharoAutoFillIgnoreStats');
        this.autoFillIgnoreStats = storedIgnore !== null ? JSON.parse(storedIgnore) : true;

        // Restore auto-filled answer keys from localStorage so they survive page reloads
        const savedAutoFilled = localStorage.getItem('sharoAutoFilledAnswers');
        this.autoFilledAnswers = new Set(savedAutoFilled ? JSON.parse(savedAutoFilled) : []);

        const storedMaxChoices = localStorage.getItem('sharoMaxDisplayedChoices');
        this.MAX_DISPLAYED_CHOICES = storedMaxChoices !== null ? parseInt(storedMaxChoices) : 10;

        const storedBracketEnabled = localStorage.getItem('sharoAutoBracketEnabled');
        this.autoBracketEnabled = storedBracketEnabled !== null ? JSON.parse(storedBracketEnabled) : true;

        this.stagnantFilters = {
            totalMin: 0, totalMax: 100,
            srsMin: 0, srsMax: 10,
            accMin: 0, accMax: 100
        };

        this.migrateData();
        this.cacheDOM();
        this.initMasteryFilters();
        this.bindEvents();
        if (this.closeModalBtn) {
            this.closeModalBtn.addEventListener('click', () => this.srsModal.classList.add('hidden'));
        }
        window.addEventListener('mousedown', (e) => {
            if (e.target === this.srsModal) this.srsModal.classList.add('hidden');
            // Only hide if we clicked outside the context menu
            if (this.contextMenu && !this.contextMenu.contains(e.target)) {
                this.hideContextMenu();
            }
        });
        window.addEventListener('contextmenu', () => {
             // Close any existing menu when right-clicking elsewhere
             // Actually, showContextMenu will handle its own display
        });
        window.addEventListener('scroll', () => this.hideContextMenu(), { passive: true });
        window.addEventListener('blur', () => this.hideContextMenu());

        // Initial call
        this.init();
        this.updateDashboard();
        this.initRecoveryButtons();
        this.updateBuildInfoWithCommitDate();
    }

    initMasteryFilters() {
        const selects = [this.todayMasterySelect, this.tomorrowMasterySelect, this.masteryLevelSelect];
        const options = [];
        options.push({ val: 'all', text: 'すべて (全Lv)' });
        
        // Single levels
        for (let i = 0; i <= 10; i++) {
            let text = `Lv.${i}`;
            if (i === 0) text += ' (未着手/忘却)';
            if (i === 10) text += ' (定着)';
            options.push({ val: i.toString(), text });
        }
        
        // Ranges: Above
        options.push({ val: 'divider-above', text: '──────────', disabled: true });
        for (let i = 1; i <= 9; i++) {
            options.push({ val: `${i}-above`, text: `Lv.${i} 以上` });
        }
        
        // Ranges: Below
        options.push({ val: 'divider-below', text: '──────────', disabled: true });
        for (let i = 1; i <= 9; i++) {
            options.push({ val: `${i}-below`, text: `Lv.${i} 以下` });
        }

        selects.forEach(select => {
            if (!select) return;
            const cur = select.value;
            select.innerHTML = '';
            options.forEach(opt => {
                const el = document.createElement('option');
                if (opt.disabled) {
                    el.disabled = true;
                    el.textContent = opt.text;
                } else {
                    el.value = opt.val;
                    el.textContent = opt.text;
                }
                select.appendChild(el);
            });
            // Try to restore value if it still exists
            if (cur && [...select.options].some(o => o.value === cur)) {
                select.value = cur;
            }
        });
    }

    checkMasteryFilter(lv, filter) {
        if (!filter || filter === 'all') return true;
        const targetLv = parseInt(filter);
        if (filter.endsWith('-below')) return lv <= targetLv;
        if (filter.endsWith('-above')) return lv >= targetLv;
        return lv === targetLv;
    }

    initRecoveryButtons() {
        const btnForceGh = document.getElementById('force-fetch-gh-btn');
        const btnForcePushGh = document.getElementById('force-push-gh-btn');
        if (btnForceGh) btnForceGh.addEventListener('click', () => this.forceSyncFromGitHub());
        if (btnForcePushGh) btnForcePushGh.addEventListener('click', () => this.forcePushToGitHub());
    }

    async forceSyncFromGitHub() {
        const config = JSON.parse(localStorage.getItem('sharoGitHubConfig') || '{}');
        if (!config.repo || !config.token || !config.path) {
            alert('GitHubの設定が完了していません。');
            return;
        }
        if (!confirm('GitHub上のデータを強制的に読み込み、現在のローカルデータを上書きします。よろしいですか？')) return;

        try {
            const remote = await this.fetchFromGitHub(config);
            if (!remote) throw new Error('GitHub上にデータが見つかりませんでした。');
            
            this.quizData = remote.quizData;
            this.questionStats = remote.questionStats;
            this.history = remote.history;
            await this.saveAll();
            localStorage.setItem('sharoLastModified', remote.lastModified || Date.now());
            alert('GitHubからの強制復元が完了しました。');
            location.reload();
        } catch (e) {
            alert('強制復元に失敗しました: ' + e.message);
        }
    }

    async forcePushToGitHub() {
        const config = JSON.parse(localStorage.getItem('sharoGitHubConfig') || '{}');
        if (!config.repo || !config.token || !config.path) {
            alert('GitHubの設定が完了していません。');
            return;
        }

        const localCount = this.getTotalQuestionCount(this.quizData);
        if (!confirm(`現在のローカルデータ（${localCount}問）をGitHubへ強制的にバックアップ（上書き保存）します。よろしいですか？`)) return;

        const btn = document.getElementById('force-push-gh-btn');
        const originalText = btn.textContent;
        btn.disabled = true;
        btn.textContent = '保存中...';

        try {
            // Need to get the latest SHA first to ensure the push works, 
            // but we don't care about the content.
            const url = `https://api.github.com/repos/${config.repo}/contents/${config.path}`;
            const headers = { 'Authorization': config.token.startsWith('ghp_') ? `token ${config.token}` : `Bearer ${config.token}` };
            
            const headRes = await fetch(url, { method: 'HEAD', headers });
            if (headRes.ok) {
                const etag = headRes.headers.get('ETag');
                this._ghFileSha = etag ? etag.replace(/"/g, '') : null;
            }

            const localData = {
                quizData: this.quizData,
                questionStats: this.questionStats,
                history: this.history,
                lastModified: Date.now()
            };

            await this.pushToGitHub(config, localData);
            localStorage.setItem('sharoLastModified', localData.lastModified);
            alert('GitHubへの強制保存が完了しました。これを復元のベースとして使用できます。');
        } catch (e) {
            alert('保存に失敗しました: ' + e.message);
        } finally {
            btn.disabled = false;
            btn.textContent = originalText;
        }
    }


    migrateData() {
        let modified = false;

        // 1. Inject/Update Survivor Sample (Check for "スリム版" or column count change)
        const currentRank = this.quizData.find(s => s.id === "survivor-rank-1");
        const defaultRank = DEFAULT_QUIZ_DATA.find(s => s.id === "survivor-rank-1");

        if (!currentRank || (currentRank.columns && currentRank.columns[1] !== "【生計維持】")) {
            if (currentRank) {
                this.quizData = this.quizData.filter(s => s.id !== "survivor-rank-1");
            }
            this.quizData.push(JSON.parse(JSON.stringify(defaultRank)));
            modified = true;
        }

        // SAFETY: Circular reference and orphaned item rescue
        const reachableIds = new Set();
        const walk = (parentId) => {
            this.quizData.filter(item => item.parentId === parentId).forEach(item => {
                if (reachableIds.has(item.id)) return; // Prevent infinite loop
                reachableIds.add(item.id);
                walk(item.id);
            });
        };
        walk(null); // Start from root

        this.quizData.forEach(set => {
            if (!set.type) set.type = 'page';
            if (set.parentId === undefined) set.parentId = null;
            if (set.isCollapsed === undefined) set.isCollapsed = false;
            if (set.isInPool === undefined) set.isInPool = true;

            if (!reachableIds.has(set.id)) {
                // Rescue item by moving to root
                set.parentId = null;
                reachableIds.add(set.id); // Mark as now reachable to prevent redundant rescue
                modified = true;
            }

            if (set.type === 'page') {
                if (!set.questions) return;
                set.questions.forEach(q => {
                    if (!q.id) { q.id = 'q-' + Math.random().toString(36).substr(2, 9) + Date.now(); modified = true; }
                    if (set.isMultiSelect && typeof q.answer === 'string') {
                        q.answer = [q.answer];
                        modified = true;
                    }
                    if (q.isInPool === undefined) {
                        q.isInPool = true;
                        modified = true;
                    }
                });
            }
        });

        // 2. Safe cleanup of questionStats
        // BUG FIX: Only cleanup stats if quizData is successfully loaded and has content.
        // If quizData is somehow empty or fallback-only but stats exist, we MUST NOT wipe them.
        if (this.quizData && this.quizData.length > 0) {
            const cleanedStats = {};
            const allIds = new Set();
            this.quizData.forEach(set => {
                const type = set.type || 'page';
                if (type === 'page' && set.questions) {
                    set.questions.forEach(q => {
                        const baseId = this.getQuestionBaseId(q.id);
                        allIds.add(baseId);
                        allIds.add(`clause-summary-${baseId}`);

                        // Detect if row has blanks even if not type clause
                        if (q.type === 'clause' || /\[\[|［［|\(\(|（（/.test(q.text || '')) {
                            const kwCount = this.extractKeywords(q.text).length;
                            for (let i = 0; i < kwCount; i++) {
                                allIds.add(`clause-${baseId}-${i}`);
                            }
                        }
                    });
                } else if (type === 'clause' && set.text) {
                    const baseId = this.getQuestionBaseId(set.id);
                    allIds.add(`clause-summary-${baseId}`);
                    const kwCount = this.extractKeywords(set.text).length;
                    for (let i = 0; i < kwCount; i++) {
                        allIds.add(`clause-${baseId}-${i}`);
                    }
                }
            });

            let hasWiped = false;
            Object.keys(this.questionStats).forEach(key => {
                // Determine base ID to check if it's still reachable
                let baseId = key;
                if (key.startsWith('clause-summary-')) baseId = key.replace('clause-summary-', '');
                else if (key.startsWith('clause-')) {
                    const parts = key.split('-');
                    // e.g. clause-p-123-0 -> baseId = p-123
                    if (parts.length >= 3) baseId = parts.slice(1, -1).join('-');
                }

                if (allIds.has(baseId) || allIds.has(key)) {
                    cleanedStats[key] = this.questionStats[key];
                    // Initialize recent history for older data
                    if (!cleanedStats[key].recent) {
                        const t = cleanedStats[key].total || 0;
                        const c = cleanedStats[key].correct || 0;
                        const count = Math.min(t, 5);
                        const r = [];
                        const recentCorrect = t > 0 ? Math.round((c / t) * count) : 0;
                        for (let i = 0; i < count; i++) r.push(i < recentCorrect ? 1 : 0);
                        cleanedStats[key].recent = r;
                    }
                    // Initialize SRS fields
                    if (cleanedStats[key].srsLevel === undefined) cleanedStats[key].srsLevel = 0;

                    // CRITICAL: Only Summaries or regular Questions should have a review schedule.
                    // Clear nextReview from individual blanks (clause-ID-index) to prevent overcounting.
                    const isBlankStat = key.startsWith('clause-') && !key.startsWith('clause-summary-');
                    if (isBlankStat) {
                        cleanedStats[key].nextReview = null;
                    } else if (cleanedStats[key].nextReview === undefined) {
                        cleanedStats[key].nextReview = null;
                    }
                } else {
                    hasWiped = true;
                }
            });

            // SAFETY: If we are about to wipe more than 50% of stats, something might be wrong.
            if (hasWiped && Object.keys(this.questionStats).length > 10 && Object.keys(cleanedStats).length < (Object.keys(this.questionStats).length / 2)) {
                console.warn("Migration safety triggered: Excessive stat cleanup prevented.");
            } else {
                this.questionStats = cleanedStats;
            }
        }

        this.isChecked = false;
        this.shuffledCache = {};

        if (modified) this.saveData(false);
        this.saveQuestionStats(false);
    }

    cacheDOM() {
        this.tabQuiz = document.getElementById('tab-quiz');
        this.tabStats = document.getElementById('tab-stats');
        this.quizView = document.getElementById('quiz-view');
        this.statsView = document.getElementById('stats-view');
        this.tocList = document.getElementById('toc-list');
        this.quizTitle = document.getElementById('quiz-title');
        this.tableHead = document.getElementById('table-head');
        this.tableBody = document.getElementById('table-body');
        this.scoreDisplay = document.getElementById('score');
        this.editModeToggle = document.getElementById('edit-mode-toggle');
        this.addFolderBtn = document.getElementById('add-folder-btn');
        this.addPageBtn = document.getElementById('add-page-btn');
        this.addClauseBtn = document.getElementById('add-clause-btn');
        this.batchAddClauseBtn = document.getElementById('batch-add-clause-btn');
        this.batchDeleteSidebarBtn = document.getElementById('batch-delete-sidebar-btn');
        this.addRowBtn = document.getElementById('add-row-btn');
        this.addColumnBtn = document.getElementById('add-column-btn');
        this.clearDataBtn = document.getElementById('clear-data-btn');
        this.deletePageBtn = document.getElementById('delete-page-btn');
        this.clonePageBtn = document.getElementById('clone-page-btn');
        this.checkAnswersBtn = document.getElementById('check-answers-btn');
        this.checkManualOnlyBtn = document.getElementById('check-manual-only-btn');
        this.resetWrongBtn = document.getElementById('reset-wrong-btn');
        this.resetMinStreakBtn = document.getElementById('reset-min-streak-btn');
        this.resetAllBtn = document.getElementById('reset-all-btn');
        this.flashModeBtn = document.getElementById('flash-mode-btn');
        this.peekAnswersBtn = document.getElementById('peek-answers-btn');
        this.masteryBoard = document.getElementById('mastery-board');
        this.autoFillShortcutBtn = document.getElementById('auto-fill-shortcut-btn-sidebar');

        this.homeBtn = document.getElementById('home-btn');
        this.homeDashboard = document.getElementById('home-dashboard');
        this.quizArea = document.getElementById('quiz-area');
        this.dueListContainer = document.getElementById('due-questions-container');
        this.dueListBody = document.getElementById('due-questions-body');
        this.dueCard = document.getElementById('due-card');
        this.startClauseOneReviewBtn = document.getElementById('start-clause-one-review-btn');
        this.startClauseReviewBtn = document.getElementById('start-clause-review-btn');
        this.startPageReviewBtn = document.getElementById('start-page-review-btn');
        this.startTomorrowClauseReviewBtn = document.getElementById('start-tomorrow-clause-review-btn');
        this.startTomorrowPageReviewBtn = document.getElementById('start-tomorrow-page-review-btn');
        this.sidebarSrsDueCount = document.getElementById('sidebar-srs-due-count');
        this.sidebarStartClauseOneReviewBtn = document.getElementById('sidebar-start-clause-one-review-btn');
        this.sidebarStartClauseReviewBtn = document.getElementById('sidebar-start-clause-review-btn');
        this.sidebarStartPageReviewBtn = document.getElementById('sidebar-start-page-review-btn');

        this.totalAccuracy = document.getElementById('total-accuracy');
        this.totalAnsweredDisplay = document.getElementById('total-answered');
        this.historyBody = document.getElementById('history-body');
        this.weakQuestionsBody = document.getElementById('weak-questions-body');
        this.stagnantQuestionsBody = document.getElementById('stagnant-questions-body');
        this.genWeakBtn = document.getElementById('gen-weak-btn');
        this.genStagnantBtn = document.getElementById('gen-stagnant-btn');
        this.genWeakClauseBtn = document.getElementById('gen-weak-clause-btn');
        this.genRareBtn = document.getElementById('gen-rare-btn');
        this.genRandomBtn = document.getElementById('gen-random-btn');
        this.genMasteryBtn = document.getElementById('gen-mastery-btn');
        this.masteryLevelSelect = document.getElementById('mastery-level-select');
        this.genSRSClauseBtn = document.getElementById('gen-srs-clause-btn');
        this.genSRSPageBtn = document.getElementById('gen-srs-page-btn');
        this.sidebarGenSRSClauseBtn = document.getElementById('sidebar-gen-srs-clause-btn');
        this.sidebarGenSRSPageBtn = document.getElementById('sidebar-gen-srs-page-btn');
        this.sidebarGenStagnantBtn = document.getElementById('sidebar-gen-stagnant-btn');

        this.chartBtns = {
            accuracy: document.getElementById('show-accuracy-btn'),
            frequency: document.getElementById('show-frequency-btn'),
            errors: document.getElementById('show-errors-btn')
        };
        this.sidebar = document.getElementById('sidebar');
        this.sidebarContent = document.getElementById('quiz-sidebar-content');
        this.menuToggle = document.getElementById('menu-toggle');
        this.sidebarCloseBtn = document.getElementById('sidebar-close-btn');

        // Data management
        this.exportJsonBtn = document.getElementById('export-json-btn');
        this.importJsonBtn = document.getElementById('import-json-btn');
        this.sidebarExportBtn = document.getElementById('sidebar-export-json-btn');
        this.sidebarImportBtn = document.getElementById('sidebar-import-json-btn');
        this.exportCsvBtn = document.getElementById('export-csv-btn');
        this.importCsvBtn = document.getElementById('import-csv-btn');
        this.dataImportInput = document.getElementById('data-import-input');
        this.dataStatusMsg = document.getElementById('data-status-msg');
        this.understandingMap = document.getElementById('understanding-map');
        this.srsModal = document.getElementById('srs-modal');
        this.srsInfo = document.getElementById('srs-info');
        this.srsModalTitle = document.getElementById('srs-modal-title');
        this.closeModalBtn = document.getElementById('close-modal');
        this.srsDetailChart = null;
        this.batchAddModal = document.getElementById('batch-add-modal');
        this.batchAddText = document.getElementById('batch-add-text');
        this.executeBatchAddBtn = document.getElementById('execute-batch-add-btn');
        this.closeBatchModalBtn = document.getElementById('close-batch-modal');
        this.clauseEditor = document.getElementById('clause-editor');

        this.clauseTextEditor = document.getElementById('clause-text-editor');
        this.clauseDummiesEditor = document.getElementById('clause-dummies-editor');
        this.clauseDisplay = document.getElementById('clause-display');
        this.tableWrapper = document.querySelector('.table-wrapper');
        this.columnControls = document.querySelector('.column-controls');
        this.tableControls = document.querySelector('.table-controls');
        this.insertTableBtn = document.getElementById('insert-table-btn');
        this.clearPoolBtn = document.getElementById('clear-pool-btn');
        this.selectAllPoolBtn = document.getElementById('select-all-pool-btn');
        this.collapseAllBtn = document.getElementById('collapse-all-btn');
        this.expandAllBtn = document.getElementById('expand-all-btn');
        this.showSelectedGraphBtn = document.getElementById('show-selected-graph-btn');
        this.globalKeywordBank = document.getElementById('global-keyword-bank');

        // GitHub Sync UI
        this.ghTokenInput = document.getElementById('gh-token');
        this.ghRepoInput = document.getElementById('gh-repo');
        this.ghPathInput = document.getElementById('gh-path');
        this.ghSyncStatus = document.getElementById('github-sync-status');
        this.ghSaveConfigBtn = document.getElementById('gh-save-config-btn');
        this.ghSyncNowBtn = document.getElementById('gh-sync-now-btn');
        this.sidebarGhSyncBtn = document.getElementById('sidebar-gh-sync-btn');

        // Auto-fill UI
        this.autoFillToggle = document.getElementById('auto-fill-toggle');
        this.autoFillThresholdInput = document.getElementById('auto-fill-threshold');
        this.autoFillIgnoreStatsToggle = document.getElementById('auto-fill-ignore-stats');
        this.maxChoicesInput = document.getElementById('max-displayed-choices');
        this.flashIntervalInput = document.getElementById('flash-interval-input');
        this.autoBracketToggle = document.getElementById('auto-bracket-toggle');
        this.srsIntervalsDisplay = document.getElementById('srs-intervals-display');
        this.contextMenu = document.getElementById('context-menu');
        this.startNightlyReviewBtn = document.getElementById('start-nightly-review-btn');
        this.nightlyErrorCountDisplay = document.getElementById('nightly-error-count');

        // Stagnant filters
        this.stagnantFilterElements = {
            totalMin: document.getElementById('stagnant-filter-total-min'),
            totalMax: document.getElementById('stagnant-filter-total-max'),
            totalVal: document.getElementById('stagnant-filter-total-val'),
            srsMin: document.getElementById('stagnant-filter-srs-min'),
            srsMax: document.getElementById('stagnant-filter-srs-max'),
            srsVal: document.getElementById('stagnant-filter-srs-val'),
            accMin: document.getElementById('stagnant-filter-acc-min'),
            accMax: document.getElementById('stagnant-filter-acc-max'),
            accVal: document.getElementById('stagnant-filter-acc-val')
        };
        this.batchDeleteBtn = document.getElementById('batch-delete-btn');
        this.deleteConfirmModal = document.getElementById('delete-confirm-modal');
        this.deleteTargetList = document.getElementById('delete-target-list');
        this.executeDeleteBtn = document.getElementById('execute-delete-btn');
        this.cancelDeleteBtn = document.getElementById('cancel-delete-btn');
        this.closeDeleteModalBtn = document.getElementById('close-delete-modal');
        this.nextPageBtn = document.getElementById('next-page-btn');
        this.todayMasterySelect = document.getElementById('today-mastery-select');
        this.tomorrowMasterySelect = document.getElementById('tomorrow-mastery-select');
    }

    bindEvents() {
        if (this.tabQuiz) {
            this.tabQuiz.addEventListener('click', () => {
                // If on dashboard, specifically look for the first learnable item in TOC
                if (this.currentSetId === null && this.tocList) {
                    const firstLink = this.tocList.querySelector('a:not(.folder-item)');
                    if (firstLink) {
                        firstLink.click();
                        return;
                    }
                }
                this.switchView('quiz');
            });
        }
        if (this.tabStats) this.tabStats.addEventListener('click', () => this.switchView('stats'));
        if (this.clearPoolBtn) {
            this.clearPoolBtn.addEventListener('click', () => this.clearAllPoolSelections());
        }
        if (this.selectAllPoolBtn) {
            this.selectAllPoolBtn.addEventListener('click', () => this.selectAllPoolSelections());
        }
        if (this.collapseAllBtn) {
            this.collapseAllBtn.addEventListener('click', () => this.collapseAllFolders());
        }
        if (this.expandAllBtn) {
            this.expandAllBtn.addEventListener('click', () => this.expandAllFolders());
        }
        if (this.showSelectedGraphBtn) {
            this.showSelectedGraphBtn.addEventListener('click', () => this.showSelectedProgressGraph());
        }
        if (this.editModeToggle) {
            this.editModeToggle.addEventListener('change', (e) => {
                this.isEditMode = e.target.checked;
                document.body.classList.toggle('edit-mode', this.isEditMode);
                this.updateTitleEditability();
                this.resetQuiz(); this.renderTOC(); this.renderTable();
            });
        }
        if (this.checkAnswersBtn) this.checkAnswersBtn.addEventListener('click', () => this.batchCheckAnswers());
        if (this.startNightlyReviewBtn) this.startNightlyReviewBtn.addEventListener('click', () => this.generateNightlyReview());
        if (this.checkManualOnlyBtn) this.checkManualOnlyBtn.addEventListener('click', () => this.batchCheckAnswers(true));
        if (this.resetWrongBtn) this.resetWrongBtn.addEventListener('click', () => this.resetWrongAnswers());
        if (this.resetMinStreakBtn) this.resetMinStreakBtn.addEventListener('click', () => this.resetMinStreakAnswers());
        if (this.resetAllBtn) this.resetAllBtn.addEventListener('click', () => {
            // Explicit full reset: clear auto-fill tracking too
            this.autoFilledAnswers.clear();
            this.saveAutoFilledAnswers();
            this.resetQuiz();
        });
        if (this.flashModeBtn) {
            this.flashModeBtn.addEventListener('click', () => {
                if (this.flashTimer) {
                    this.stopFlashMode();
                } else {
                    this.startFlashMode();
                }
            });
        }
        if (this.peekAnswersBtn) {
            this.peekAnswersBtn.addEventListener('click', () => {
                const isRevealed = document.body.classList.toggle('answers-revealed');
                this.peekAnswersBtn.innerHTML = isRevealed ? '👁️ 答えを隠す' : '👁️ 答えを表示する';
                this.peekAnswersBtn.classList.toggle('active', isRevealed);
            });
        }
        if (this.autoFillShortcutBtn) {
            this.autoFillShortcutBtn.addEventListener('click', () => {
                const thresholds = [1, 2, 3, 5, 10];
                if (!this.autoFillEnabled) {
                    this.autoFillEnabled = true;
                    this.autoFillThreshold = 1;
                } else {
                    const idx = thresholds.indexOf(this.autoFillThreshold);
                    if (idx !== -1 && idx < thresholds.length - 1) {
                        this.autoFillThreshold = thresholds[idx + 1];
                    } else {
                        this.autoFillEnabled = false;
                        this.autoFillThreshold = 5; // default for next toggle on
                    }
                }

                localStorage.setItem('sharoAutoFillEnabled', JSON.stringify(this.autoFillEnabled));
                localStorage.setItem('sharoAutoFillThreshold', this.autoFillThreshold);

                if (this.autoFillToggle) this.autoFillToggle.checked = this.autoFillEnabled;
                if (this.autoFillThresholdInput) this.autoFillThresholdInput.value = this.autoFillThreshold;

                this.updateAutoFillShortcutUI();
                this.resetQuiz(); // Refresh current queston/page with new auto-fill state
            });
        }
        if (this.todayMasterySelect) {
            this.todayMasterySelect.addEventListener('change', () => this.updateDashboard());
        }
        if (this.tomorrowMasterySelect) {
            this.tomorrowMasterySelect.addEventListener('change', () => this.updateDashboard());
        }
        if (this.addFolderBtn) this.addFolderBtn.addEventListener('click', () => this.addNewFolder());
        if (this.addPageBtn) this.addPageBtn.addEventListener('click', () => this.addNewPage());
        if (this.addClauseBtn) this.addClauseBtn.addEventListener('click', () => this.addNewClausePage());
        if (this.batchAddClauseBtn) this.batchAddClauseBtn.addEventListener('click', () => this.showBatchAddModal());
        if (this.batchDeleteSidebarBtn) this.batchDeleteSidebarBtn.addEventListener('click', () => this.showSidebarDeleteConfirmModal());
        if (this.executeBatchAddBtn) this.executeBatchAddBtn.addEventListener('click', () => this.executeBatchAdd());
        if (this.closeBatchModalBtn) this.closeBatchModalBtn.addEventListener('click', () => {
            if (this.batchAddModal) this.batchAddModal.classList.add('hidden');
        });
        if (this.addRowBtn) this.addRowBtn.addEventListener('click', () => this.addNewRow());
        if (this.addColumnBtn) this.addColumnBtn.addEventListener('click', () => this.addNewColumn());
        if (this.clearDataBtn) this.clearDataBtn.addEventListener('click', () => this.clearData());
        if (this.deletePageBtn) this.deletePageBtn.addEventListener('click', () => this.deleteCurrentPage());
        if (this.clonePageBtn) this.clonePageBtn.addEventListener('click', () => this.cloneCurrentPage());
        if (this.batchDeleteBtn) this.batchDeleteBtn.addEventListener('click', () => this.showDeleteConfirmModal());
        if (this.executeDeleteBtn) this.executeDeleteBtn.addEventListener('click', () => this.executeDeleteSelectedQuestions());
        if (this.cancelDeleteBtn) this.cancelDeleteBtn.addEventListener('click', () => { if (this.deleteConfirmModal) this.deleteConfirmModal.classList.add('hidden'); });
        if (this.closeDeleteModalBtn) this.closeDeleteModalBtn.addEventListener('click', () => { if (this.deleteConfirmModal) this.deleteConfirmModal.classList.add('hidden'); });
        if (this.nextPageBtn) this.nextPageBtn.addEventListener('click', () => this.loadNextPage());

        // PDFからのペースト時に改行を賢く処理する
        if (this.clauseTextEditor) {
            this.clauseTextEditor.addEventListener('paste', (e) => {
                e.preventDefault();
                const raw = (e.clipboardData || window.clipboardData).getData('text');
                
                // ◯○〇【□■ の記号があれば、その前で改行を入れる（PDFの単一行化対策）
                let text = raw.replace(/([◯○〇【□■])/g, '\n$1');
                
                // 改行を一旦正規化
                text = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
                
                // 1. 各行を処理
                const lines = text.split('\n');
                let processed = '';
                
                for (let i = 0; i < lines.length; i++) {
                    const line = lines[i].trim();
                    if (!line) continue;
                    
                    // 行頭が「イ)」「a)」「1)」「(1)」「ア.」「◯」「【」「□」などの記号で始まるか判定
                    const isItemStart = /^[◯○〇【□■]|^[a-z0-9\u3040-\u309F\u30A0-\u30FF一-龠][\).）．]|[0-9]\)|^[（(][0-9イアa-z][）)]/.test(line);
                    
                    if (isItemStart && processed !== '') {
                        // 項目頭なら改行を入れる
                        processed += '\n' + line;
                    } else {
                        // それ以外（続きの文など）なら結合する
                        processed += (processed === '' ? '' : '') + line;
                    }
                }
                
                const start = this.clauseTextEditor.selectionStart;
                const end = this.clauseTextEditor.selectionEnd;
                const current = this.clauseTextEditor.value;
                this.clauseTextEditor.value = current.substring(0, start) + processed + current.substring(end);
                
                // カーソル位置の更新
                this.clauseTextEditor.selectionStart = this.clauseTextEditor.selectionEnd = start + processed.length;
                this.clauseTextEditor.dispatchEvent(new Event('input'));
            });
        }

        if (this.insertTableBtn && this.clauseTextEditor) {
            this.insertTableBtn.addEventListener('click', () => {
                const template = "\n| 項目 | 内容 | 備考 |\n| --- | --- | --- |\n| [[キーワード1]] | 内容1 | 備考1 |\n| [[キーワード2]] | 内容2 | 備考2 |\n| 結合例(横) | > | 備考 |\n| 結合例(縦) | 内容 | 備考 |\n| ^ | 内容 | 備考 |\n";
                const start = this.clauseTextEditor.selectionStart;
                const end = this.clauseTextEditor.selectionEnd;
                const text = this.clauseTextEditor.value;
                this.clauseTextEditor.value = text.substring(0, start) + template + text.substring(end);
                this.clauseTextEditor.dispatchEvent(new Event('input')); // Trigger update
            });
        }

        if (this.genWeakBtn) this.genWeakBtn.addEventListener('click', () => this.generateSpecialQuiz('weak'));
        if (this.genStagnantBtn) this.genStagnantBtn.addEventListener('click', () => this.scrollToStagnantList());
        if (this.sidebarGenStagnantBtn) this.sidebarGenStagnantBtn.addEventListener('click', () => this.scrollToStagnantList());
        
        const sidebarDrillBtn = document.getElementById('sidebar-article-drill-btn');
        if (sidebarDrillBtn) sidebarDrillBtn.addEventListener('click', () => this.openArticleDrillModal());
        
        const dashboardDrillBtn = document.getElementById('dashboard-article-drill-btn');
        if (dashboardDrillBtn) dashboardDrillBtn.addEventListener('click', () => this.openArticleDrillModal());

        if (this.genWeakClauseBtn) {
            this.genWeakClauseBtn.addEventListener('click', () => this.generateSpecialQuiz('clause-weak'));
        }
        if (this.genRareBtn) this.genRareBtn.addEventListener('click', () => this.generateSpecialQuiz('rare'));
        if (this.genRandomBtn) this.genRandomBtn.addEventListener('click', () => this.generateSpecialQuiz('random'));
        if (this.genMasteryBtn) this.genMasteryBtn.addEventListener('click', () => this.generateSpecialQuiz('mastery'));
        if (this.genSRSClauseBtn) this.genSRSClauseBtn.addEventListener('click', () => this.generateSpecialQuiz('srs-clause'));
        if (this.genSRSPageBtn) this.genSRSPageBtn.addEventListener('click', () => this.generateSpecialQuiz('srs-page'));
        if (this.sidebarGenSRSClauseBtn) this.sidebarGenSRSClauseBtn.addEventListener('click', () => this.generateSpecialQuiz('srs-clause'));
        if (this.sidebarGenSRSPageBtn) this.sidebarGenSRSPageBtn.addEventListener('click', () => this.generateSpecialQuiz('srs-page'));

        if (this.chartBtns) {
            Object.keys(this.chartBtns).forEach(mode => {
                if (this.chartBtns[mode]) {
                    this.chartBtns[mode].addEventListener('click', () => {
                        this.chartMode = mode;
                        this.updateChartTabs();
                        this.renderChart();
                    });
                }
            });
        }
        if (this.tocList) {
            this.tocList.addEventListener('click', (e) => {
                if (e.target.tagName === 'A') {
                    e.preventDefault();
                    const id = e.target.getAttribute('href').substring(1);
                    const item = this.quizData.find(s => s.id === id);
                    if (item && item.type === 'folder') {
                        this.toggleFolder(id);
                    } else if (item) {
                        this.isAutoGenerated = false;
                        this.currentSetId = id;
                        this.loadSet(id);

                        // Auto-close sidebar on mobile/tablet after selection
                        if (window.innerWidth <= 1024 && this.sidebar) {
                            this.sidebar.classList.remove('open');
                        }
                    }
                }
            });
        }

        // Update TOC real-time when editing title
        if (this.quizTitle) {
            this.quizTitle.addEventListener('input', () => {
                if (this.isEditMode && !this.isAutoGenerated) {
                    const set = this.quizData.find(s => s.id === this.currentSetId);
                    if (set) {
                        set.title = this.quizTitle.textContent.trim();
                        this.renderTOC();
                    }
                }
            });

            this.quizTitle.addEventListener('blur', () => {
                if (this.isEditMode && !this.isAutoGenerated) {
                    const set = this.quizData.find(s => s.id === this.currentSetId);
                    if (set) {
                        set.title = this.quizTitle.textContent.trim();
                        this.saveData();
                    }
                }
            });
        }
        if (this.sidebar && this.menuToggle) {
            this.menuToggle.addEventListener('click', () => {
                if (window.innerWidth > 1024) {
                    // Desktop: Toggle permanent hide/show
                    document.body.classList.toggle('sidebar-hidden');
                } else {
                    // Mobile/Tablet: Toggle slide-in drawer
                    this.sidebar.classList.toggle('open');
                }
            });
        }
        if (this.sidebarCloseBtn) {
            this.sidebarCloseBtn.addEventListener('click', () => {
                if (window.innerWidth > 1024) {
                    document.body.classList.add('sidebar-hidden');
                } else {
                    this.sidebar.classList.remove('open');
                }
            });
        }
        if (this.homeBtn) {
            this.homeBtn.addEventListener('click', () => {
                this.isAutoGenerated = false;
                this.loadSet(null);
                this.switchView('quiz');
            });
        }
        if (this.dueCard) {
            this.dueCard.addEventListener('click', (e) => {
                if (e.target.tagName !== 'BUTTON') this.toggleDueList();
            });
        }
        if (this.startClauseOneReviewBtn) {
            this.startClauseOneReviewBtn.addEventListener('click', () => this.generateDueReview('clause', 1));
        }
        if (this.sidebarStartClauseOneReviewBtn) {
            this.sidebarStartClauseOneReviewBtn.addEventListener('click', () => this.generateDueReview('clause', 1));
        }
        if (this.startClauseReviewBtn) {
            this.startClauseReviewBtn.addEventListener('click', () => this.generateDueReview('clause', 1));
        }
        if (this.sidebarStartClauseReviewBtn) {
            this.sidebarStartClauseReviewBtn.addEventListener('click', () => this.generateDueReview('clause', 1));
        }
        if (this.startPageReviewBtn) {
            this.startPageReviewBtn.addEventListener('click', () => this.generateDueReview('page', 10));
        }
        if (this.startTomorrowClauseReviewBtn) {
            this.startTomorrowClauseReviewBtn.addEventListener('click', () => this.generateDueReview('clause', 1, 1));
        }
        if (this.startTomorrowPageReviewBtn) {
            this.startTomorrowPageReviewBtn.addEventListener('click', () => this.generateDueReview('page', 10, 1));
        }
        if (this.sidebarStartPageReviewBtn) {
            this.sidebarStartPageReviewBtn.addEventListener('click', () => this.generateDueReview('page', 10));
        }

        // Data management events
        if (this.exportJsonBtn) this.exportJsonBtn.addEventListener('click', () => this.exportToJSON());
        if (this.importJsonBtn && this.dataImportInput) {
            this.importJsonBtn.addEventListener('click', () => { this.dataImportInput.accept = '.json'; this.dataImportInput.click(); });
        }
        if (this.sidebarExportBtn) this.sidebarExportBtn.addEventListener('click', () => this.exportToJSON());
        if (this.sidebarImportBtn && this.dataImportInput) {
            this.sidebarImportBtn.addEventListener('click', () => { this.dataImportInput.accept = '.json'; this.dataImportInput.click(); });
        }
        if (this.exportCsvBtn) this.exportCsvBtn.addEventListener('click', () => this.exportToCSV());
        if (this.importCsvBtn && this.dataImportInput) {
            this.importCsvBtn.addEventListener('click', () => { this.dataImportInput.accept = '.csv'; this.dataImportInput.click(); });
        }
        if (this.dataImportInput) {
            this.dataImportInput.addEventListener('change', (e) => this.handleFileImport(e));
        }

        // GitHub Sync events
        if (this.ghSaveConfigBtn) this.ghSaveConfigBtn.addEventListener('click', () => this.saveGitHubConfig());
        if (this.ghSyncNowBtn) this.ghSyncNowBtn.onclick = () => this.syncWithGitHub();
        if (this.sidebarGhSyncBtn) this.sidebarGhSyncBtn.addEventListener('click', () => this.syncWithGitHub());

        // Auto-fill settings events
        if (this.autoFillToggle) {
            this.autoFillToggle.onchange = () => {
                this.autoFillEnabled = this.autoFillToggle.checked;
                localStorage.setItem('sharoAutoFillEnabled', JSON.stringify(this.autoFillEnabled));
                this.updateAutoFillShortcutUI();
                this.resetQuiz(); // Refresh current question/page
            };
        }
        if (this.autoFillThresholdInput) {
            this.autoFillThresholdInput.onchange = () => {
                const val = parseInt(this.autoFillThresholdInput.value);
                this.autoFillThreshold = !isNaN(val) ? val : 5;
                localStorage.setItem('sharoAutoFillThreshold', this.autoFillThreshold);
                this.resetQuiz(); // Refresh current question/page
            };
        }
        if (this.autoFillIgnoreStatsToggle) {
            this.autoFillIgnoreStatsToggle.onchange = () => {
                this.autoFillIgnoreStats = this.autoFillIgnoreStatsToggle.checked;
                localStorage.setItem('sharoAutoFillIgnoreStats', JSON.stringify(this.autoFillIgnoreStats));
                this.resetQuiz(); // Refresh
            };
        }
        if (this.maxChoicesInput) {
            this.maxChoicesInput.value = this.MAX_DISPLAYED_CHOICES;
            this.maxChoicesInput.onchange = () => {
                const val = parseInt(this.maxChoicesInput.value);
                this.MAX_DISPLAYED_CHOICES = !isNaN(val) && val > 0 ? val : 10;
                localStorage.setItem('sharoMaxDisplayedChoices', this.MAX_DISPLAYED_CHOICES);
                this.shuffledCache = {}; 
                this.renderTable();
            };
        }
        if (this.flashIntervalInput) {
            this.flashIntervalInput.value = this.flashInterval;
            this.flashIntervalInput.onchange = () => {
                const val = parseInt(this.flashIntervalInput.value);
                this.flashInterval = !isNaN(val) && val > 0 ? val : 5;
                localStorage.setItem('sharoFlashInterval', this.flashInterval);
                if (this.flashTimer) {
                    this.stopFlashMode();
                    this.startFlashMode();
                }
            };
        }

        if (this.autoBracketToggle) {
            this.autoBracketToggle.onchange = () => {
                this.autoBracketEnabled = this.autoBracketToggle.checked;
                localStorage.setItem('sharoAutoBracketEnabled', JSON.stringify(this.autoBracketEnabled));
            };
        }

        // Recovery button for internal backup
        const forceRestoreBtn = document.getElementById('force-restore-internal-btn');
        if (forceRestoreBtn) {
            forceRestoreBtn.addEventListener('click', () => this.checkAndOfferRecovery(true));
        }

        // Stagnant filter events
        ['totalMin', 'totalMax', 'srsMin', 'srsMax', 'accMin', 'accMax'].forEach(key => {
            const el = this.stagnantFilterElements[key];
            if (el) {
                el.addEventListener('input', (e) => {
                    const val = parseInt(e.target.value);
                    this.stagnantFilters[key] = val;
                    this.updateStagnantFilterDisplays();
                    this.renderStats();
                });
            }
        });
    }

    updateExamCountdown() {
        const getExamDate = (year) => {
            const d = new Date(year, 7, 1); // August 1st
            const offset = d.getDay() === 0 ? 0 : 7 - d.getDay();
            return new Date(year, 7, 1 + offset + 21); // 4th Sunday
        };
        const now = new Date();
        let year = now.getFullYear();
        let examDate = getExamDate(year);
        // If today is past exam day (with a small buffer for end of day), target next year
        if (now.getTime() > examDate.getTime() + 24 * 60 * 60 * 1000) {
            year++;
            examDate = getExamDate(year);
        }
        
        const diffMs = examDate.getTime() - now.getTime();
        const daysLeft = Math.ceil(diffMs / (1000 * 60 * 60 * 24));
        
        const elDays = document.getElementById('exam-days-left');
        const elLabel = document.getElementById('exam-date-label');
        if (elDays && elLabel) {
            elDays.textContent = daysLeft;
            elLabel.textContent = `${year}年8月第4日曜日 (${examDate.getMonth()+1}/${examDate.getDate()})`;
        }
    }

    initSidebarResizer() {
        const resizer = document.getElementById('sidebar-resizer');
        const sidebar = document.getElementById('sidebar');
        if (!resizer || !sidebar) return;

        let isResizing = false;

        // Restore saved width if any
        const savedWidth = localStorage.getItem('sharoSidebarWidth');
        if (savedWidth) {
            sidebar.style.setProperty('--sidebar-width', savedWidth);
        }

        resizer.addEventListener('mousedown', (e) => {
            isResizing = true;
            resizer.classList.add('is-resizing');
            document.body.style.cursor = 'col-resize';
            // Disable text selection while dragging
            document.body.style.userSelect = 'none';
        });

        
const app = new App(); console.log(app.getMappedLawId("412AC0000000018", "Sp-At_20"));